---
kind: "operation"
client: "rug-cli 0.28.0"
editor:
  name: "AddTypeScriptCommandHandler"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.23.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "37b4b2dd89d507bde31a028d2bd9fbc23300e979"
    sha: "37b4b2d"
  parameters:
    - "handlerName": "TravisBuildRug"
    - "description": "command handler to trigger build of a Rug archive on Travis CI"
    - "intent": "travis build"

